# Generated by Django 4.0 on 2022-02-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcat',
            new_name='category',
        ),
    ]
