# Generated by Django 4.0 on 2022-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_rename_subcat_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategoryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
