# Generated by Django 4.0 on 2022-02-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0003_subcategory_images_alter_subcategoryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryimage',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_image', to='subcategory.subcategory'),
        ),
    ]
